### Get all TodoItems
GET http://localhost:8090/restapi/TodoItemDtos
Authorization: Bearer {{access_token}}

### Get a single TodoItem with an id of 1
GET http://localhost:8090/restapi/TodoItemDtos/1

### POST a new TodoItem with valid data
POST http://localhost:8090/restapi/TodoItemDtos
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "task": "Start DMIT2015 Assignment 6",
  "done": false
}

### Post a new TodoItem with invalid data
POST http://localhost:8090/restapi/TodoItemDtos
Content-Type: application/json

{
  "task": "     ",
  "done": false
}

### Get a single TodoItem with an id of 4
GET http://localhost:8090/restapi/TodoItemDtos/4

### Update TodoItem with an id of 4 with valid data
PUT http://localhost:8090/restapi/TodoItemDtos/4
Content-Type: application/json

{
  "id": 4,
  "task": "Commit DMIT2015 Assignment 6 update",
  "done": true,
  "version": 1
}

### Delete an TodoItem with an id of 2
DELETE http://localhost:8090/restapi/TodoItemDtos/2

### Delete an TodoItem with an id of 4
DELETE http://localhost:8090/restapi/TodoItemDtos/4